[2025-01-28T01:17:00.932+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-28T01:17:01.034+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: raw_api_sales_data.store_sales_data_raw manual__2025-01-28T01:13:09.925968+00:00 [queued]>
[2025-01-28T01:17:01.069+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: raw_api_sales_data.store_sales_data_raw manual__2025-01-28T01:13:09.925968+00:00 [queued]>
[2025-01-28T01:17:01.071+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-28T01:17:01.588+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): store_sales_data_raw> on 2025-01-28 01:13:09.925968+00:00
[2025-01-28T01:17:01.636+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2397) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-28T01:17:01.639+0000] {standard_task_runner.py:72} INFO - Started process 2409 to run task
[2025-01-28T01:17:01.645+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'raw_api_sales_data', 'store_sales_data_raw', 'manual__2025-01-28T01:13:09.925968+00:00', '--job-id', '109', '--raw', '--subdir', 'DAGS_FOLDER/raw/dag_load_sales_data_to_db.py', '--cfg-path', '/tmp/tmpjnprabte']
[2025-01-28T01:17:01.649+0000] {standard_task_runner.py:105} INFO - Job 109: Subtask store_sales_data_raw
[2025-01-28T01:17:12.985+0000] {cli_action_loggers.py:177} WARNING - Failed to log action (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-01-28T01:17:16.407+0000] {job.py:229} INFO - Heartbeat recovered after 15.68 seconds
[2025-01-28T01:17:16.526+0000] {task_command.py:467} INFO - Running <TaskInstance: raw_api_sales_data.store_sales_data_raw manual__2025-01-28T01:13:09.925968+00:00 [running]> on host 1de8b92bf5f9
[2025-01-28T01:17:16.925+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='raw_api_sales_data' AIRFLOW_CTX_TASK_ID='store_sales_data_raw' AIRFLOW_CTX_EXECUTION_DATE='2025-01-28T01:13:09.925968+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-28T01:13:09.925968+00:00'
[2025-01-28T01:17:16.928+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-28T01:17:16.929+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-28T01:17:16.931+0000] {logging_mixin.py:190} INFO - Current task name:store_sales_data_raw state:running start_date:2025-01-28 01:17:01.037709+00:00
[2025-01-28T01:17:16.933+0000] {logging_mixin.py:190} INFO - Dag name:raw_api_sales_data and current dag run status:running
[2025-01-28T01:17:16.935+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-28T01:17:23.338+0000] {database_helpers.py:20} INFO - Connected to PostgreSQL database.
[2025-01-28T01:17:23.797+0000] {database_helpers.py:20} INFO - Connected to PostgreSQL database.
[2025-01-28T01:17:23.800+0000] {database_helpers.py:99} INFO - Data successfully inserted into raw_layer.sales.
[2025-01-28T01:17:23.802+0000] {raw_store_sales_data.py:32} INFO - Successfuly inserted data into raw_layer.sales table
[2025-01-28T01:17:23.809+0000] {database_helpers.py:30} INFO - Closed the database connection.
[2025-01-28T01:17:23.818+0000] {raw_store_sales_data.py:38} INFO - Database Closed
[2025-01-28T01:17:23.819+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-28T01:17:23.961+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-28T01:17:23.963+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=raw_api_sales_data, task_id=store_sales_data_raw, run_id=manual__2025-01-28T01:13:09.925968+00:00, execution_date=20250128T011309, start_date=20250128T011701, end_date=20250128T011723
[2025-01-28T01:17:24.010+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-28T01:17:24.011+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-28T01:17:24.013+0000] {logging_mixin.py:190} INFO - Dag name:raw_api_sales_data queued_at:2025-01-28 01:13:10.101814+00:00
[2025-01-28T01:17:24.015+0000] {logging_mixin.py:190} INFO - Task hostname:1de8b92bf5f9 operator:PythonOperator
[2025-01-28T01:17:24.059+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-28T01:17:24.126+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-28T01:17:24.133+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
